version: 2
jobs:
  test:
    docker:
      - image: circleci/python:2.7
      - image: circleci/mongo:3.2
    steps:
      - checkout

      - restore_cache:
          name: Restore installed dependencies
          keys:
            - v2-pip-{{ arch }}-{{ .Branch }}-{{ checksum "python-dep-install.sh" }}
            - v2-pip-{{ arch }}-{{ .Branch }}-
            - v2-pip-{{ arch }}-

      - run:
          name: Install dependencies with pip
          command: |
            virtualenv virtenv
            . virtenv/bin/activate
            ./python-dep-install.sh
            pip install coveralls
            pip install "mock==1.0.1"
            pip install "nose-parameterized==0.5.0"

      - run:
          name: Coverage
          command: |
            cd src
            coverage run --branch --source=wstore ./manage.py test --noinput --with-xunit --nologcapture -v 2
            coverage xml --omit="*urls*" -i

      - save_cache:
          name: Save dependencies cache
          key: v2-pip-{{ arch }}-{{ .Branch }}-{{ checksum "python-dep-install.sh" }}
          paths:
            - virtenv

  docker-build:
    docker:
      - image: docker:18.01.0-ce-git
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Login to docker
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Build the docker image
          command: |
            docker build -t charging7 .

      - run:
          name: Tag the docker image
          command: |
            docker tag charging7 digicatsynch/charging7:$CIRCLE_SHA1
            docker tag charging7 digicatsynch/charging7:ci-$CIRCLE_BUILD_NUM
            docker tag charging7 digicatsynch/charging7:${CIRCLE_BRANCH##feature/}

      - run:
          name: Push the docker image
          command: |
            docker push digicatsynch/charging7:$CIRCLE_SHA1
            docker push digicatsynch/charging7:ci-$CIRCLE_BUILD_NUM
            docker push digicatsynch/charging7:${CIRCLE_BRANCH##feature/}

    release-version:
      docker:
        - image: docker:18.01.0-ce-git
      steps:
        - checkout

        - setup_remote_docker

        - run:
            name: Login to docker
            command: |
              docker login -u $DOCKER_USER -p $DOCKER_PASS

        - run:
            name: Build the docker image
            command: |
              docker build -t digicatsynch/charging7:${CIRCLE_TAG##v} .

        - run:
            name: Push the docker image
            command: |
              docker push digicatsynch/charging7:${CIRCLE_TAG##v}
workflows:
  version: 2
  logic-proxy:
    jobs:
      - test
      - docker-build:
          requires:
            - test
  tagged-build:
    jobs:
      - release-version:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
